"""initial_schema

Revision ID: a504b2bccfd6
Revises: 
Create Date: 2026-04-03 16:37:39.154575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a504b2bccfd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    op.create_table(
        'usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('hashed_password', sa.String(length=200), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False, server_default='user'),
        sa.Column('ativo', sa.Boolean(), nullable=True, server_default='true'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_usuarios_id', 'usuarios', ['id'])
    op.create_index('ix_usuarios_username', 'usuarios', ['username'], unique=True)

    op.create_table(
        'colaboradores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('documento', sa.String(length=50), nullable=False),
        sa.Column('empresa', sa.String(length=100), nullable=True),
        sa.Column('setor', sa.String(length=100), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=True, server_default='true'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_colaboradores_id', 'colaboradores', ['id'])
    op.create_index('ix_colaboradores_documento', 'colaboradores', ['documento'], unique=True)

    op.create_table(
        'quartos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('capacidade', sa.Integer(), nullable=False),
        sa.Column('ocupacao_atual', sa.Integer(), nullable=True, server_default='0'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_quartos_id', 'quartos', ['id'])
    op.create_index('ix_quartos_numero', 'quartos', ['numero'], unique=True)

    op.create_table(
        'alocacoes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('colaborador_id', sa.Integer(), nullable=True),
        sa.Column('quarto_id', sa.Integer(), nullable=True),
        sa.Column('data_entrada', sa.Date(), nullable=False),
        sa.Column('data_saida', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id']),
        sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_alocacoes_id', 'alocacoes', ['id'])

    op.create_table(
        'manutencoes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quarto_id', sa.Integer(), nullable=True),
        sa.Column('descricao', sa.String(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True, server_default='Aberto'),
        sa.Column('data_abertura', sa.TIMESTAMP(), nullable=True),
        sa.Column('data_fechamento', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_manutencoes_id', 'manutencoes', ['id'])


def downgrade() -> None:
    op.drop_table('manutencoes')
    op.drop_table('alocacoes')
    op.drop_table('quartos')
    op.drop_table('colaboradores')
    op.drop_table('usuarios')

