"""add_role_to_usuario

Revision ID: da16e173bbff
Revises: a504b2bccfd6
Create Date: 2026-04-03 16:40:41.826369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da16e173bbff'
down_revision: Union[str, Sequence[str], None] = 'a504b2bccfd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('usuarios', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))

    # role já criado na migration inicial (a504b2bccfd6)
    pass

    # role já criado na migration inicial (a504b2bccfd6)
    pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###
